"""Interfaz del repositorio de usuarios (dominio)."""
from __future__ import annotations

from typing import Protocol

from domain.entities.user import User


class UserRepository(Protocol):
    async def add(self, user: User) -> User: ...
    async def get_by_name(self, name: str) -> User | None: ...
    async def list_all(self) -> tuple[User, ...]: ...
    async def update(self, user: User) -> None: ...
    async def delete(self, user_id: int) -> None: ...
    async def count(self) -> int: ...